type Mutation {
  login(username: String!, password: String!): Response!

  loginWithEmail(email: String!, code: String!, key: String!): Response!

  logout: Response!

  register(
    username: String!, 
    nickname: String!, 
    avatar: String!, 
    gender: String!, 
    location: String!, 
    birthday: Date!,
    email: String!,
    statement: String!,
    u_key: String!,
    e_key: String!
  ): Response!
  
  checkUsername(username: String!): Response!

  checkUsernameValid(username: String!): Response!
  
  setPassword(email: String!, password: String!, key: String!): Response!

  sendEmailCode(email: String!): Response!

  sendEmailLoginCode(email: String!): Response!

  ackEmail(email: String!, code: String!, key: String!): Response!

  uploadSingleImage(image: Upload!): Response!

  createArticle(
    title: String!,
    abstract: String!,
    content: String!,
    categoryIds: [Int]!
  ): Response!

  checkArticleIdValid(id: Int!): Response!

  sendComment(content: String!, articleId: Int!): Response!

  articleStar(articleId: Int!, status: Boolean!): Response!

  articleLike(articleId: Int!, status: Boolean!): Response!

  changeUserInfo(
    email: String!,
    key: String!,
    nickname: String
    location: String
    gender: String
    birthday: Date
    avatar: String
    statement: String
    eduBG: JSON
    emRecords: JSON
    secQuestions: JSON
    categoryIds: [Int]!
    industryIds: [Int]!
  ): Response!

  userConcern(userId: Int!, status: Boolean!): Response!

  categoryStar(categoryId: Int!, status: Boolean!): Response!

  industryStar(industryId: Int!, status: Boolean!): Response!

  sendMessage(userId: Int!, message: String!): Response!
}