type Mutation {
  login(username: String!, password: String!): Response!

  loginWithEmail(email: String!, code: String!, key: String!): Response!

  logout(username: String!): Response!

  register(
    username: String!, 
    nickname: String!, 
    avatar: String!, 
    gender: String!, 
    location: String!, 
    birthday: Date!,
    email: String!,
    statement: String!,
    u_key: String!,
    e_key: String!
  ): Response!
  
  checkUsername(username: String!): Response!

  checkUsernameValid(username: String!): Response!
  
  setPassword(email: String!, password: String!, key: String!): Response!

  sendEmailCode(email: String!): Response!

  sendEmailLoginCode(email: String!): Response!

  ackEmail(email: String!, code: String!, key: String!): Response!

  uploadSingleImage(image: Upload!): Response!

  createArticle(
    title: String!,
    abstract: String!,
    content: String!,
    username: String!,
    token: String!,
    categoryIds: [Int]!
  ): Response!

  checkArticleIdValid(id: Int!): Response!

  sendComment(username: String!, token: String!, content: String!, articleId: Int!): Response!

  articleStar(username: String!, token: String!, articleId: Int!, status: Boolean!): Response!

  articleLike(username: String!, token: String!, articleId: Int!, status: Boolean!): Response!

  changeUserInfo(
    email: String!,
    key: String!,
    nickname: String
    location: String
    gender: String
    birthday: Date
    avatar: String
    statement: String
    eduBG: JSON
    emRecords: JSON
    secQuestions: JSON
    categoryIds: [Int]!
    industryIds: [Int]!
  ): Response!

  userConcern(username: String!, token: String!, userId: Int!, status: Boolean!): Response!
}