type Query {
  init: Response!

  users(usernames: [String], categoryIds: [Int], industryIds: [Int]): Response!

  categorys: Response!

  industrys: Response!

  articles(idList: [Int], categoryIds: [Int]): Response!

  messages(userId: Int!): Response!
}