type User {
  id: ID!
  username: String!
  nickname: String!
  location: String
  gender: String!
  user_type: Int
  birthday: Date
  industrys: [Int]!
  register_at: Date!
  last_login_at: Date!
  avatar: String
  status: Int
  statement: String
  email: String!
  eduBG: [EduBG]!
  articles: [Article]!
  emRecords: [EmRecord]!
  categorys: [Int]!
  concerned: [Concern]!
  concern: [Concern]
  likes: [Like]!
  collections: [Collect]!
  dynamics: [Dynamics]!
  secQuestion: [SecQuestion]!
}

type EduBG {
  id: Int!
  school: String
  major: String
  degree: Degree
  user_id: Int!
}

type EmRecord {
  id: Int!
  company: String!
  position: String!
  user_id: Int!
}

type SecQuestion {
  question: String!
  answer: String!
  user: User!
}

type Industry {
  id: ID!
  name: String
  description: String
  image: String
  users: [JSON]
}

type Category {
  id: ID!
  subject: String
  description: String
  users: [JSON]
  image: String
}

type Like {
  id: ID!
  create_time: Date
  user_id: Int
  article_id: Int
  comment_id: Int
  user: User
  article: Article
  comment: Comment
}

type Collect {
  id: ID!
  create_time: Date
  user_id: Int
  article_id: Int
  user: User
  article: Article
}

type Concern {
  id: ID!
  user_id: Int
  concerned_user_id: Int
  user: User
  concern_user: User
}

type Article {
  id: ID!
  title: String!
  abstract: String!
  image: String
  content: JSON
  release_time: Date
  last_modify_time: Date
  user_id: Int
  user: User
  project_link: [String]
  categorys: [Int]!
  industrys: [Int]!
  comments: [Comment]
  likes: [Like]
  collections: [Collect]
}

type Comment {
  id: ID!
  content: String
  user_id: String
  article_id: String
  user: User
  article: Article
  comments: [JSON]
  comment: Comment
  create_time: Date
  likes: [Like]
}

type Application {
  id: Int
  user_id: Int
  apply_time: Date
  deal_user_id: Int
  deal_time: Date
  status: Int
  reason: String
  subject: String
  name: String
  description: String
  image: String
}

type Message {
  id: ID!
  sendUser: User
  acceptUser: User
  s_user_id: Int
  a_user_id: Int
  content: String
  send_time: Date
}

type SessionInfo {
  username: String
  token: String
  isRefresh: Boolean
}

type UploadInfo {
  filename: String!
  isSuccess: Boolean!
  size: Int!
  uri: String!
}

type Error {
  path: String
  message: String
}

type Extension {
  operator: String!
  errors: [Error]!
}

type Response {
  key: String
  token: String

  username: String
  url: String
  sessionInfo: SessionInfo

  user: User
  article: Article

  users: [User]
  categorys: [Category]
  industrys: [Industry]
  articles: [Article]

  message: Message
  messages: [Message]

  applications: [Application]

  isSuccess: Boolean!
  extension: Extension!
  code: Int
}

type Dynamics {
  type: DynamcisType!
  article: Article
  comment: Comment
  user: User
  do_at: Date!
}

enum Degree {
  BACHELOR
  MASTER
  DOCTOR
  OTHER
}

enum DynamcisType {
  ARTICLE_CREATE
  ARTICLE_MODIFY
  ARTICLE_LIKE
  ARTICLE_COLLECT

  COMMENT_CREATE
  COMMENT_LIKE

  USER_CONCERN
}

type File {
  filename: String!
  mimetype: String!
  encoding: String!
}

scalar Date
scalar JSON
scalar JSONObject